language: java
sudo: false # faster builds

before_install:
  - pip install --user codecov

script:
  - cd plugin-code
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov

